# -*- coding: utf-8 -*-
"""Assigment 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18DFmAkX7tER5FEYaIFKtHzfpxWR-rY-I
"""

import pandas as pd
import requests
import seaborn as sns
import matplotlib.pyplot as plt


DATA_URL = "https://tourism.api.opendatahub.com/v1/Accommodation"

response = requests.get(DATA_URL)

print(response.status_code)
print(response.text[:500])

data = response.json()

print(type(data))
print(data.keys())

print(len(data["Items"]))

df = pd.DataFrame(data["Items"])

print(df.shape)
print(df.head())

print(df.columns) #no column named Municipality

print(df["LocationInfo"].iloc[0])

print(df["LocationInfo"].iloc[0]["MunicipalityInfo"]["Name"]["it"]) #we have to extract Municipality from LocationInfo

df["Municipality"] = df["LocationInfo"].apply(
    lambda x: x["MunicipalityInfo"]["Name"]["it"]
)
print(df[["Municipality"]])

response = requests.get(
    DATA_URL,
    params={"pagesize": 1000, "pagenumber": 1}
)

#Before, the API was giving us only 10 accommodations per page.

#Now we are asking for 1000 per page, so instead of needing 1,613 pages, we need roughly 17 pages to get all 16,125 accommodations.

data = response.json()

print("Page:", data["CurrentPage"])
print("Accommodations:", len(data["Items"]))
print("Total:", data["TotalResults"])

all_items = []

print(all_items)

for page in range(1, 18):
    print(page)

all_items = []

for page in range(1, 18):
    response = requests.get(
        DATA_URL,
        params={"pagesize": 1000, "pagenumber": page}
    )

    data = response.json()

    all_items.extend(data["Items"])

print(len(all_items))

df = pd.DataFrame(all_items)

print(df.shape)

print(df["LocationInfo"].isna().sum())

df["Municipality"] = df["LocationInfo"].apply(
    lambda x: x["MunicipalityInfo"]["Name"]["en"]
    if x["MunicipalityInfo"] is not None
    else "Unknown"
)
# some municipality don't have accomodations so in that case it will print unknown

print(df["Municipality"].isna().sum())

municipality_counts = df["Municipality"].value_counts()

print(municipality_counts.head(10))

print(df["Municipality"].nunique())  #different value of municipality

municipality_counts.head(15)

top15 = municipality_counts.head(15)

plt.figure(figsize=(12, 6))

sns.barplot(
    x=top15.index,
    y=top15.values
)

plt.xlabel("Municipality")
plt.ylabel("Number of accommodations")
plt.title("Top 15 Municipalities by Number of Accommodations")
plt.xticks(rotation=45)

plt.show()

municipality_counts.head(10)

top10 = municipality_counts.head(10)

plt.figure(figsize=(12, 6))

sns.barplot(
    x=top10.index,
    y=top10.values
)

plt.xlabel("Municipality")
plt.ylabel("Number of accommodations")
plt.title("Top 10 Municipalities by Number of Accommodations")
plt.xticks(rotation=45)

plt.show()

!pip install streamlit

import streamlit as st

print(st.__version__)

import streamlit as st

# Municipality filter
selected_municipality = st.selectbox(
    "Choose a municipality",
    top10.index
)

# Filter the full dataset
filtered_df = df[
    df["Municipality"] == selected_municipality
]

# Count accommodation types
type_counts = filtered_df["AccoType"].value_counts()

st.write(f"AccoType in {selected_municipality}")
st.bar_chart(type_counts)